// <auto-generated />
namespace CatchMeIfYouCan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AdminRoleAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdminRoleAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202206191620068_Admin-Role-Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
